#
variables:
  dockerId: rummyze  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: test  # Replace with the name of the image you want to publish
  pswd: PdtAMv1iKlTT6KdxrvfosTdwJfJM=ndW  # Replace with the password form the Azure Container Registry

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    npm install
    # npm audit fix  --force
    # npm run build
  displayName: 'Run a multi-line script'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: zip

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: test-file'

- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
    # docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)

